### ISSUE TITLE
Garmin Virb support

### ISSUE THREAD

**Issue by M0nk3yofdoom** [b1g0n3/MyCameraRemote#1]
Can this remote be used to control the Garmin Virb camera range?

**Comment by b1g0n3** [comment]
Hi,

For the moment, the Garmin Virb camera is not supported, because I haven't
time for this and I don't have this camera in my bag ;)

Sorry for that

2016-12-08 14:22 GMT+01:00 M0nk3yofdoom <notifications@github.com>:

**Comment by M0nk3yofdoom** [comment]
fair enough :) I might look at incorporating it as well as a simple p2p camera option as well. I am also looking at having the video screen appear in the notifications. Love your work.
